### GraphQL Mutation
POST https://api.pipefy.com/graphql
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQaXBlZnkiLCJpYXQiOjE3Njk0MzQ1NDgsImp0aSI6Ijk5YTNiNTA0LWFmZmEtNDc5OS1iZDczLTgxYmY5NWRiNTE3MCIsInN1YiI6MzA3NDE2NzcwLCJ1c2VyX3R5cGUiOiJhdXRoZW50aWNhdGVkIn0.UUb8I1w6jHaXM2qYXsyvSbM2bURtsQIpvQZkeIK71WAp_jMB-POZatIopbyjxvaiy-Nvm4uFJj5wT-9kKrgoNA
Content-Type: application/json

{ "query": "mutation {moveCardToPhase(input: {card_id: 1287993879destination_phase_id: 339198365}) {card {current_phase {id}}}}" }

curl -i https://api.pipefy.com/graphql \
  -H "Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQaXBlZnkiLCJpYXQiOjE3Njk0MzQ1NDgsImp0aSI6Ijk5YTNiNTA0LWFmZmEtNDc5OS1iZDczLTgxYmY5NWRiNTE3MCIsInN1YiI6MzA3NDE2NzcwLCJ1c2VyX3R5cGUiOiJhdXRoZW50aWNhdGVkIn0.UUb8I1w6jHaXM2qYXsyvSbM2bURtsQIpvQZkeIK71WAp_jMB-POZatIopbyjxvaiy-Nvm4uFJj5wT-9kKrgoNA" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  --data '{"query":"mutation {moveCardToPhase(input: {card_id: 1287993879destination_phase_id: 339198365}) {card {current_phase {id}}}}"}'